# Generated by Django 4.1.2 on 2022-12-14 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
