# Generated by Django 4.1.2 on 2022-12-14 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contest_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='created',
            new_name='submitted_date',
        ),
    ]
